### ISSUE TITLE
enable joining without start

### ISSUE THREAD

**Issue by david-guenault** [naparuba/kunai#4] opened 2015-01-02 18:38 UTC
when using kunai join the kunai daemon should be started before trying to join.

**Comment by naparuba** [comment] 2015-01-03 12:04
won't fix. This is by design. If you want you an setup the seeds parameter in the local.json file instead :)

**Closed by naparuba** 2015-01-03 12:04 UTC

**Comment by david-guenault** [comment] 2015-01-03 14:08
Oookkkkk did not see this ....

**Comment by naparuba** [comment] 2015-01-03 21:39
it's in the article ;)
